print("\nPlease enter the following information: ")
print()
first_name= input("First name: ")
last_name= input("Last name: ")
email= input("Email address: ")
phone_number= input("Phone number (xxx-xxx-xxxx): ")
job_title= input("Job title: ")
ID_number= input("ID Number: ")
Hair_color= input("Hair color: ")
Eye_color= input("Eye color: ")
month= input("Birth Month: ")
training= input("Training (yes or no): ")

print("\nThe ID card is: ")
print("-" * 40)
print("{1}, {0}".format(first_name.capitalize(), last_name.upper()))
print(job_title.title())
print("ID: " + ID_number)
print()
print(email.lower())
print(phone_number)
print()

print(f"Hair: {Hair_color.capitalize():15} Eyes: {Eye_color.capitalize()}")
print(f"Month: {month.capitalize():14} Training: {training.capitalize()}")

print("-" * 40)
print()
