print()
print("Please enter the following:")
print()
adjective = input("adjective: ")
animal = input("animal: ")
verb1 = input("verb: ")
exclamation = input("exclamation: ")
verb2 = input("verb: ")
verb3 = input("verb: ")
noun= input("noun: ")
noun2= input("noun (not proper): ")
job= input("name of a job: ")
print()
print("Your story is: ")
print()
print(f"The other day, I was really in trouble. It all started when I saw a very") 
print (f'{adjective} {animal} {verb1} down the hallway. "{exclamation.capitalize()}!" I yelled. But all')
#I used single quotes here because double doesn't work when I also have to use double around the exclamation statement.
print(f"I could think to do was to {verb2} over and over. Miraculously,")
print(f"that caused it to stop, but not before it tried to {verb3}")
print(f"right in front of my family.")
print(f"But that wasn't even the half of it! My little brother decided to")
print(f"pick up a {noun} and throw it at the {animal} while it was still trying to {verb3}!")
print(f"Well he obviously missed (he's a bad throw) and hit the {noun2} right next to the {job}'s office!")
print(f"We all had a good laugh after that. We learned that we should never mess with a {animal}")
print(f"if there is a {job} around.")
print()


